# Generated by Django 3.1.7 on 2021-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmarks',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_bookmarks'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_order'),
        ),
        migrations.AddConstraint(
            model_name='recipe_tag',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='unique_recipe_tag'),
        ),
    ]
